on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI Test
jobs:
  test:
    strategy:
      matrix:
        php-versions:
          - 7.3
    runs-on: ubuntu-latest
    steps:
      - name: install rdkafka
        run: sudo apt-get install -y librdkafka-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          tools: pecl
          extensions: rdkafka
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
